### ISSUE TITLE
ICS file support (calendar integration)

### ISSUE THREAD

**Issue by mvbs23** [clovenski/nijisanji-en-schedules#1]
Hello. I'm glad to know about this project.

Not an issue, but I don't know how to label it otherwise.

Is it possible that the schedules of each liver to be synchronized with ICS files (used by Google Calendar and others) in order to receive personalized and updated notifications with our own calendar apps?

I would personally love something like that.

**Comment by clovenski** [comment]
Hey.

Thanks for the suggestion!
There is no support for that right now, but I can look into it and see if it's something that's feasible with the current setup.

I'll let you know if I get anywhere in my research and if I can come up with an ETA on this.

Otherwise, you can always check this website during the day, click on the streams you'd like a notification for, and use YouTube's own notification system.

**Comment by clovenski** [comment]
Hey @mvbs23 , so I did some research and thought about the feature.

I believe that implementing this will cost me more than I'm comfortable with; and looking into Google Calendar / Outlook, it looks like they only synchronize with the ICS file every few hours. The schedules info is updated every 5 minutes, so you'd definitely be missing some streams with that workflow.

I'll put this feature on the TODO list though because I think it's something to revisit later on if this project gets somewhere.

Sincerely,
Joel

**Comment by mvbs23** [comment]
Thank you for considering it!

**Comment by clovenski** [comment]
Hey @mvbs23 ! So I've got a chance to work on this the past few days, and I may have something that could work for you.
I'll be able to provide the ICS links if you let me know which 3 livers you'd like to see.

After that, you can let me know if it'll work for you, then I'll continue working on finalizing this feature and will eventually have instructions and links on the README of this repository!

![image](https://user-images.githubusercontent.com/32505043/210291646-935d3bbc-6ce7-4f6f-9695-2ec911fa5de6.png)

**Comment by mvbs23** [comment]
Amazing! Thank you very much.
The picture of the calendar looks really good, that's exactly what I imagined.

So I'll give you my feedback within some days. I want to try with the schedules of these livers:
- Pomu Rainpuff,
- Rosemi Lovelock, and
- Shu Yamino.

**Comment by clovenski** [comment]
Here you go.

Pomu: https://calendar.google.com/calendar/ical/40f11158b6dd9e4e1b0aea34e6be8849c7d1ea617e445b3c900feb8e2e131344%40group.calendar.google.com/public/basic.ics

Rosemi-sama:
https://calendar.google.com/calendar/ical/5282acfe1997b7a850c1ec9b517879550e5487144fd358023455826033dc6941%40group.calendar.google.com/public/basic.ics

Shu:
https://calendar.google.com/calendar/ical/fb314faaba5ba00e88399bcd28c8630422ebb040dbb0c0937acca21771433a89%40group.calendar.google.com/public/basic.ics

Things that I've found during testing:
- the color coding on those calendars don't persist to whoever is subscribing to them; i.e. once you subscribe to those links, the color for the calendar events won't be the same as mine, adjust them as you'd like
- I found that the subscription synchronizes the changes pretty often, which I thought it would take hours and make it impractical. Those calendars get updated every 5 minutes, so if it looks like it doesn't update often on your side, you can look into [this solution](https://github.com/derekantrican/GAS-ICS-Sync) (I haven't tried it out myself though)

Also, to keep cost low, the window where the events will show is +/- 1 day from now. So you only really see the most recent streams, currently live streams, and the near-upcoming streams.


Let me know if there's any issue.
Cheers!

**Comment by mvbs23** [comment]
Hi! It worked for me flawlessly, with frequent updates and personalized notifications. I'm genuinely satisfied!

The fact that it just shows recent streams —following the same idea as the main website— also helps to keep the calendar clean, so personally I really appreciate that as well.

Thank you very much for your efforts!

**Comment by clovenski** [comment]
Awesome! Thank _you_ for bringing this feature up - it was interesting to take it on!

I'll work on finalizing everything and in v0.5.0 there'll be instructions / notes in the [changelog](https://github.com/clovenski/nijisanji-en-schedules/blob/main/assets/CHANGELOG.md) regarding the ics files for the rest of the livers.

**Comment by clovenski** [comment]
Implemented in v0.5.0 - https://github.com/clovenski/nijisanji-en-schedules/blob/main/assets/gcal/README.md
